name: Debian

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  debian-test:
    runs-on: ubuntu-latest
    container:
      image: "debian:latest"

    steps:
    - uses: actions/checkout@v4

    # Error Check
    - name: Run install.sh
      run: |
        apt-get update
        ./install.sh debian --all
