name: Debian

on:
  push:
    branches: [ main ]
    paths:
      - "**.sh"
      - "**.bash"
      - "**linux**"
      - "**debian**"
  pull_request:
    branches: [ main ]
    paths:
      - "**.sh"
      - "**.bash"
      - "**linux**"
      - "**debian**"

jobs:
  debian-test:
    runs-on: ubuntu-latest
    container:
      image: "debian:latest"

    steps:
    - uses: actions/checkout@v4

    # Error Check
    - name: Run install.sh
      run: |
        apt-get update
        ./install.sh debian --all
      env:
        DEBCONF_NOWARNINGS: yes
