name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Error Check
    - name: Run install.sh
      run: sudo ${GITHUB_WORKSPACE}/install.sh ubuntu --all

    - name: Load .bash_profile
      run: |
        bash ~/.bash_profile 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi
