name: Windows

on:
  push:
    branches: [ main ]
    paths:
      - "**.ps1"
      - "**windows**"
  pull_request:
    branches: [ main ]
    paths:
      - "**.ps1"
      - "**windows**"

jobs:
  windows-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install winget
      uses: Cyberboss/install-winget@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Error Check
    - name: Run install.ps1
      shell: powershell
      run: .\install.ps1 --all

    - name: Check properly installed
      shell: pwsh
      run: |
          if (!(Test-Path "C:\Program Files\Netcat")) { Write-Error "Netcat not found."; exit 1 }
          if (!(Get-Module -ListAvailable -Name PSReadLine)) { Write-Error "PSReadLine not found."; exit 1 }
          if (!(Get-Module -ListAvailable -Name Terminal-Icons)) { Write-Error "Terminal-Icons not found."; exit 1 }
          if (!(Test-Path "${env:USERPROFILE}\Documents\Powershell\Microsoft.Powershell_profile.ps1")) { Write-Error "PWSH Profile not found."; exit 1 }
          if (!(Test-Path "${env:USERPROFILE}\Documents\WindowsPowershell\Microsoft.Powershell_profile.ps1")) { Write-Error "Powershell Profile not found."; exit 1 }
          if (!(Test-Path "${env:USERPROFILE}\Documents\Powershell\Microsoft.VSCode_profile.ps1")) { Write-Error "VSCode Profile not found."; exit 1 }
